version: '3.8'
services:
  opentutor:
    container_name: opentutor
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  cypress:
    container_name: cypress
    depends_on:
      - opentutor
    build:
      context: cypress
    environment:
      - "CYPRESS_BASE_URL=http://opentutor/admin"
      - "CYPRESS_SNAPSHOT_DIFF_DIR=/app/cypress/snapshots/snapshot_failed_diffs"
